{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "a42b0836-0201-4c8d-8021-bd5a8ef5383e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Team_Leucine Information\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>Slack_username</th>\n",
       "      <th>Country</th>\n",
       "      <th>Hobby</th>\n",
       "      <th>Affiliation</th>\n",
       "      <th>Fav_gene_sequence</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Chioma Nnadi</td>\n",
       "      <td>Chioma</td>\n",
       "      <td>Nigeria</td>\n",
       "      <td>Writing</td>\n",
       "      <td>none</td>\n",
       "      <td>ACGTTTTGTAAATGTTGTGCTGTTAACACTGCAAATAAACTTGGTA...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kashish Arora</td>\n",
       "      <td>Kashish</td>\n",
       "      <td>India</td>\n",
       "      <td>Reading</td>\n",
       "      <td>University of Glasgow</td>\n",
       "      <td>GAACATGTCCCAACATGTTG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Keola Merl Joanes</td>\n",
       "      <td>Keola</td>\n",
       "      <td>India</td>\n",
       "      <td>Reading</td>\n",
       "      <td>PCCAS</td>\n",
       "      <td>GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAA...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Lavinia Dorothea F Joseph</td>\n",
       "      <td>Lavinia</td>\n",
       "      <td>Antigua &amp; Barbuda</td>\n",
       "      <td>Sudoku</td>\n",
       "      <td>University Mohammed V, FMPH</td>\n",
       "      <td>GTTCCAGGTAGTGCCTGAAACTACTTTTCTGAAGAAGTATAATTAA...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Atairoro Joshua</td>\n",
       "      <td>Atairoro Joshua</td>\n",
       "      <td>Nigeria</td>\n",
       "      <td>Music</td>\n",
       "      <td>None</td>\n",
       "      <td>ATGGAAGTTGTCATTTTATAAAGTCAGTAGTTTCTTTGGCAGCAAT...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Bezaleel Akinbami</td>\n",
       "      <td>B3z</td>\n",
       "      <td>Nigeria</td>\n",
       "      <td>Gaming</td>\n",
       "      <td>None</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Sharon Addy</td>\n",
       "      <td>Sharon Addy</td>\n",
       "      <td>Ghana</td>\n",
       "      <td>Repairng damaged electronics</td>\n",
       "      <td>None</td>\n",
       "      <td>UGGAAUGUAAAGAAGUAUGUAU</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                        Name   Slack_username            Country                         Hobby                  Affiliation                                  Fav_gene_sequence\n",
       "0               Chioma Nnadi           Chioma            Nigeria                       Writing                         none  ACGTTTTGTAAATGTTGTGCTGTTAACACTGCAAATAAACTTGGTA...\n",
       "1              Kashish Arora          Kashish              India                       Reading        University of Glasgow                               GAACATGTCCCAACATGTTG\n",
       "2          Keola Merl Joanes            Keola              India                       Reading                        PCCAS  GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAA...\n",
       "3  Lavinia Dorothea F Joseph          Lavinia  Antigua & Barbuda                        Sudoku  University Mohammed V, FMPH  GTTCCAGGTAGTGCCTGAAACTACTTTTCTGAAGAAGTATAATTAA...\n",
       "4            Atairoro Joshua  Atairoro Joshua            Nigeria                         Music                         None  ATGGAAGTTGTCATTTTATAAAGTCAGTAGTTTCTTTGGCAGCAAT...\n",
       "5          Bezaleel Akinbami              B3z            Nigeria                        Gaming                         None                                                   \n",
       "6                Sharon Addy      Sharon Addy              Ghana  Repairng damaged electronics                         None                             UGGAAUGUAAAGAAGUAUGUAU"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Import the pandas library for data manipulation\n",
    "import pandas as pd\n",
    "\n",
    "#Define list of dictionaries to store team information\n",
    "team_leucine = [\n",
    "    {\n",
    "        \"Name\": \"Chioma Nnadi\",\n",
    "        \"Slack_username\": \"Chioma\",\n",
    "       \"Country\": \"Nigeria\",\n",
    "        \"Hobby\": \"Writing\",\n",
    "        \"Affiliation\": \"none\",\n",
    "        \"Fav_gene_sequence\": \"ACGTTTTGTAAATGTTGTGCTGTTAACACTGCAAATAAACTTGGTAGCAAACACTTCCA\"\n",
    "    },\n",
    "    {\n",
    "       \"Name\": \"Kashish Arora\",\n",
    "       \"Slack_username\": \"Kashish\",\n",
    "       \"Country\": \"India\",\n",
    "       \"Hobby\": \"Reading\",\n",
    "        \"Affiliation\": \"University of Glasgow\",\n",
    "        \"Fav_gene_sequence\": \"GAACATGTCCCAACATGTTG\"\n",
    "    },\n",
    "    {\n",
    "       \"Name\": \"Keola Merl Joanes\",\n",
    "        \"Slack_username\": \"Keola\",\n",
    "        \"Country\": \"India\",\n",
    "       \"Hobby\": \"Reading\",\n",
    "        \"Affiliation\": \"PCCAS\",\n",
    "       \"Fav_gene_sequence\": \"GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGCAA\"\n",
    "    },\n",
    "    {\n",
    "         \"Name\": \"Lavinia Dorothea F Joseph\",\n",
    "        \"Slack_username\": \"Lavinia\",\n",
    "        \"Country\": \"Antigua & Barbuda\",\n",
    "       \"Hobby\": \"Sudoku\",\n",
    "        \"Affiliation\": \"University Mohammed V, FMPH\",\n",
    "       \"Fav_gene_sequence\": \"GTTCCAGGTAGTGCCTGAAACTACTTTTCTGAAGAAGTATAATTAAAAGTAATCTTGTTTTGAGAA\"\n",
    "    },\n",
    "     {\n",
    "       \"Name\": \"Atairoro Joshua\",\n",
    "        \"Slack_username\": \"Atairoro Joshua\",\n",
    "        \"Country\": \"Nigeria\",\n",
    "       \"Hobby\": \"Music\",\n",
    "        \"Affiliation\": \"None\",\n",
    "       \"Fav_gene_sequence\": \"ATGGAAGTTGTCATTTTATAAAGTCAGTAGTTTCTTTGGCAGCAATGCCAGGAAAGGCTCTGAGGAA\"\n",
    "    },\n",
    "     {\n",
    "       \"Name\": \"Bezaleel Akinbami\",\n",
    "        \"Slack_username\": \"B3z\",\n",
    "        \"Country\": \"Nigeria\",\n",
    "       \"Hobby\": \"Gaming\",\n",
    "        \"Affiliation\": \"None\",\n",
    "       \"Fav_gene_sequence\": \"\"\n",
    "    },\n",
    "     {\n",
    "       \"Name\": \"Sharon Addy\",\n",
    "        \"Slack_username\": \"Sharon Addy\",\n",
    "        \"Country\": \"Ghana\",\n",
    "       \"Hobby\": \"Repairng damaged electronics\",\n",
    "        \"Affiliation\": \"None\",\n",
    "       \"Fav_gene_sequence\": \"UGGAAUGUAAAGAAGUAUGUAU\"\n",
    "    }\n",
    "]\n",
    "\n",
    "#Convert the list of dictionaries into a pandas DataFrame\n",
    "df_team_leucine = pd.DataFrame(team_leucine)\n",
    "\n",
    "#Print the DataFrame\n",
    "print(\"Team_Leucine Information\\n\")\n",
    "\n",
    "#Import IPython.display to present team information in a well structured table\n",
    "from IPython.display import display\n",
    "display(df_team_leucine)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "bef0e77b-aa2c-425e-aa7f-f49dd9e354a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Team_Leucine Information\n",
      "\n",
      "Name: Chioma Nnadi\n",
      "Slack_username: Chioma\n",
      "Country: Nigeria\n",
      "Hobby: Writing\n",
      "Affiliation: none\n",
      "Favorite Gene DNA Sequence: ACGTTTTGTAAATGTTGTGCTGTTAACACTGCAAATAAACTTGGTAGCAAACACTTCCA\n",
      "------------------------------------------------------------------------------------------------------------------------\n",
      "Name: Kashish Arora\n",
      "Slack_username: Kashish\n",
      "Country: India\n",
      "Hobby: Reading\n",
      "Affiliation: University of Glasgow\n",
      "Favorite Gene DNA Sequence: GAACATGTCCCAACATGTTG\n",
      "------------------------------------------------------------------------------------------------------------------------\n",
      "Name: Keola Merl Joanes\n",
      "Slack_username: Keola\n",
      "Country: India\n",
      "Hobby: Reading\n",
      "Affiliation: PCCAS\n",
      "Favorite Gene DNA Sequence: GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGCAA\n",
      "------------------------------------------------------------------------------------------------------------------------\n",
      "Name: Lavinia Dorothea F Joseph\n",
      "Slack_username: Lavinia\n",
      "Country: Antigua & Barbuda\n",
      "Hobby: Sudoku\n",
      "Affiliation: University Mohammed V, FMPH\n",
      "Favorite Gene DNA Sequence: GTTCCAGGTAGTGCCTGAAACTACTTTTCTGAAGAAGTATAATTAAAAGTAATCTTGTTTTGAGAA\n",
      "------------------------------------------------------------------------------------------------------------------------\n",
      "Name: Atairoro Joshua\n",
      "Slack_username: Atairoro Joshua\n",
      "Country: Nigeria\n",
      "Hobby: Music\n",
      "Affiliation: None\n",
      "Favorite Gene DNA Sequence: ATGGAAGTTGTCATTTTATAAAGTCAGTAGTTTCTTTGGCAGCAATGCCAGGAAAGGCTCTGAGGAA\n",
      "------------------------------------------------------------------------------------------------------------------------\n",
      "Name: Bezaleel Akinbami\n",
      "Slack_username: B3z\n",
      "Country: Nigeria\n",
      "Hobby: Gaming\n",
      "Affiliation: None\n",
      "Favorite Gene DNA Sequence: \n",
      "------------------------------------------------------------------------------------------------------------------------\n",
      "Name: Sharon Addy\n",
      "Slack_username: Sharon Addy\n",
      "Country: Ghana\n",
      "Hobby: Repairng damaged electronics\n",
      "Affiliation: None\n",
      "Favorite Gene DNA Sequence: UGGAAUGUAAAGAAGUAUGUAU\n",
      "------------------------------------------------------------------------------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "print(\"Team_Leucine Information\\n\")\n",
    "for person in team_leucine:  \n",
    "    print(f\"Name: {person['Name']}\")\n",
    "    print(f\"Slack_username: {person['Slack_username']}\")\n",
    "    print(f\"Country: {person['Country']}\")\n",
    "    print(f\"Hobby: {person['Hobby']}\")\n",
    "    print(f\"Affiliation: {person['Affiliation']}\")\n",
    "    print(f\"Favorite Gene DNA Sequence: {person['Fav_gene_sequence']}\")\n",
    "    print(\"-\" * 120)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a21d554-6c5f-403f-824a-1931af3f5a32",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-panel-2023.05-py310",
   "language": "python",
   "name": "conda-env-anaconda-panel-2023.05-py310-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
